---
title: ""
output: 
  html_document:
    fig_caption: yes
    keep_md: yes
    theme: paper
    toc: yes
    toc_depth: 2
---

```{r setup, include=F}
## Setup.

knitr::opts_chunk$set(echo = T, cache = F, warning = F, message = F, size = "small")
rm(list = ls(all.names = T))
library(rmarkdown); library(knitr); library(gridExtra)
library(tidyr); library(dplyr); library(ggplot2); library(survey)
```

```{r load, include=F}
## Load data.

load("~/git/flu-survey/data/cleaning2.RData")
load("~/git/flu-survey/data/recoding.RData")  # load "datar"
df <- datar  # recoded variables
```

```{r group, include=F}
## Regroup variables.

# income
income.map <- c(rep("under $10k", 3), rep("$10k to $25k", 4),
                rep("$25k to $50k", 4), rep("$50k to $75k", 2),
                rep("$75k to $100k", 2), rep("$100k to $150k", 2),
                rep("over $150k", 2))
df$income <- code(datar$PPINCIMP, income.map, "under $10k")
income.lab <- c("under $10k", "$10k to $25k", "$25k to $50k",
                "$50k to $75k", "$75k to $100k", "$100k to $150k",
                "over $150k")
df$income <- factor(df$income, levels = income.lab)

# marital staus
marital.map <- c("single", "partnered", "partnered", "single", "single", "single")
df$marital <- code(dataf$PPMARIT, marital.map, "single")

# work status
work.map <- c(rep("unemployed", 5),
              rep("employed", 2))
df$work <- code(dataf$PPWORK, work.map, "unemployed")
```

```{r des}
## Create survey object.

options(digits = 4)
options(survey.lonely.psu = "adjust")

des <- svydesign(ids = ~1, weights = ~weight, data = df[is.na(df$weight)==F, ])
```

```{r ggplot, include=F}
## Create ggplot templates.

ptext <- theme(axis.text = element_text(size = rel(0.9)),
               axis.text.x = element_text(angle = 45, hjust = 1))

pgen <- aes(PPGENDER)
page <- aes(ppagect4)
peth <- aes(PPETHM)
pinc <- aes(income)
pedu <- aes(PPEDUCAT)
pwor <- aes(work)
pmar <- aes(marital)

```


